/* ──────────────────────────────────────────────────────
   markdownDb.js — Markdown-as-DB serializer / parser
   
   Storage keys in localStorage:
     md:tasks        → tasks.md content
     md:notes:YYYY-Www → one key per ISO week
     md:settings     → small JSON blob (nextTaskId, etc.)
   ────────────────────────────────────────────────────── */

/* ── ISO week helpers ── */
export function getISOWeek(dateStr) {
  const d = new Date(dateStr + "T12:00:00");
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const weekNo = Math.ceil(((d - yearStart) / 86400000 + 1) / 7);
  return { year: d.getUTCFullYear(), week: weekNo };
}

export function weekKey(dateStr) {
  const { year, week } = getISOWeek(dateStr);
  return `${year}-W${String(week).padStart(2, "0")}`;
}

export function weekRange(dateStr) {
  const d = new Date(dateStr + "T12:00:00");
  const day = d.getDay();
  const diffMon = d.getDate() - day + (day === 0 ? -6 : 1);
  const mon = new Date(d.getFullYear(), d.getMonth(), diffMon);
  const sun = new Date(mon);
  sun.setDate(mon.getDate() + 6);
  const fmt = (dt) =>
    dt.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  return `${fmt(mon)} – ${fmt(sun)}, ${sun.getFullYear()}`;
}

/* ── Time formatting ── */
const pad2 = (n) => String(n).padStart(2, "0");
export function fmtTime(s) {
  return `${pad2(Math.floor(s / 3600))}:${pad2(Math.floor((s % 3600) / 60))}:${pad2(s % 60)}`;
}

/* ─────────── TASKS → Markdown ─────────── */
export function tasksToMarkdown(activeTasks, completedTasks) {
  let md = `# Tasks\n\n`;
  md += `> Auto-generated by Calendar Task App. Do not reorder fields.\n\n`;

  md += `## Active\n\n`;
  if (activeTasks.length === 0) {
    md += `_No active tasks._\n\n`;
  } else {
    for (const t of activeTasks) {
      md += `### T${t.id}\n`;
      md += `- **Description:** ${t.description || "(empty)"}\n`;
      md += `- **Time:** ${fmtTime(t.timeOnTask)} (${t.timeOnTask}s)\n`;
      md += `- **Started:** ${t.startDate}\n`;
      md += `\n`;
    }
  }

  md += `## Completed\n\n`;
  const dateKeys = Object.keys(completedTasks).sort().reverse();
  if (dateKeys.length === 0) {
    md += `_No completed tasks._\n`;
  } else {
    for (const dk of dateKeys) {
      md += `### ${dk}\n\n`;
      for (const ct of completedTasks[dk]) {
        md += `#### T${ct.id}\n`;
        md += `- **Description:** ${ct.description || "(empty)"}\n`;
        md += `- **Time:** ${fmtTime(ct.timeOnTask)} (${ct.timeOnTask}s)\n`;
        md += `- **Completed:** ${ct.completedAt}\n`;
        md += `\n`;
      }
    }
  }

  return md;
}

/* ─────────── Markdown → TASKS ─────────── */
export function markdownToTasks(md) {
  const activeTasks = [];
  const completedTasks = {};

  if (!md || !md.trim()) return { activeTasks, completedTasks };

  const lines = md.split("\n");
  let section = null; // 'active' | 'completed'
  let currentDateKey = null;
  let currentTask = null;
  let parsingCompleted = false;

  for (const line of lines) {
    const trimmed = line.trim();

    // Section headers
    if (trimmed === "## Active") {
      section = "active";
      parsingCompleted = false;
      continue;
    }
    if (trimmed === "## Completed") {
      // Flush the last Active task before leaving that section; otherwise it
      // stays as currentTask and the first #### in Completed wrongly files it
      // under the first completed date (todo / in-progress tasks "become" done).
      if (currentTask && section === "active") {
        activeTasks.push(currentTask);
        currentTask = null;
      }
      section = "completed";
      parsingCompleted = true;
      continue;
    }

    // Task ID lines (### T0, #### T0)
    const taskMatch = trimmed.match(/^#{3,4}\s+T(\d+)$/);
    if (taskMatch) {
      // Save previous task
      if (currentTask) {
        if (parsingCompleted && currentDateKey) {
          if (!completedTasks[currentDateKey]) completedTasks[currentDateKey] = [];
          completedTasks[currentDateKey].push(currentTask);
        } else if (!parsingCompleted) {
          activeTasks.push(currentTask);
        }
      }
      currentTask = {
        id: parseInt(taskMatch[1]),
        description: "",
        timeOnTask: 0,
        startDate: new Date().toISOString(),
      };
      continue;
    }

    // Date key for completed section (### 2026-04-01)
    if (parsingCompleted) {
      const dateMatch = trimmed.match(/^### (\d{4}-\d{2}-\d{2})$/);
      if (dateMatch) {
        // Save previous task if any
        if (currentTask && currentDateKey) {
          if (!completedTasks[currentDateKey]) completedTasks[currentDateKey] = [];
          completedTasks[currentDateKey].push(currentTask);
          currentTask = null;
        }
        currentDateKey = dateMatch[1];
        continue;
      }
    }

    // Field parsing
    if (currentTask) {
      const descMatch = trimmed.match(/^-\s+\*\*Description:\*\*\s+(.+)$/);
      if (descMatch) {
        currentTask.description = descMatch[1] === "(empty)" ? "" : descMatch[1];
        continue;
      }
      const timeMatch = trimmed.match(/\((\d+)s\)/);
      if (timeMatch && trimmed.includes("**Time:**")) {
        currentTask.timeOnTask = parseInt(timeMatch[1]);
        continue;
      }
      const startMatch = trimmed.match(/^-\s+\*\*Started:\*\*\s+(.+)$/);
      if (startMatch) {
        currentTask.startDate = startMatch[1];
        continue;
      }
      const compMatch = trimmed.match(/^-\s+\*\*Completed:\*\*\s+(.+)$/);
      if (compMatch) {
        currentTask.completedAt = compMatch[1];
        currentTask.dateKey = currentDateKey;
        continue;
      }
    }
  }

  // Save final task
  if (currentTask) {
    if (parsingCompleted && currentDateKey) {
      if (!completedTasks[currentDateKey]) completedTasks[currentDateKey] = [];
      completedTasks[currentDateKey].push(currentTask);
    } else if (!parsingCompleted) {
      activeTasks.push(currentTask);
    }
  }

  return { activeTasks, completedTasks };
}

/* ─────────── NOTES → Markdown ─────────── */
export function noteToMarkdown(wk, range, content) {
  return `# ${wk} — ${range}\n\n${content}`;
}

export function markdownToNote(md) {
  if (!md || !md.trim()) return "";
  const lines = md.split("\n");
  // Skip the H1 header line and the blank line after it
  let start = 0;
  if (lines[0]?.startsWith("# ")) start = 1;
  if (lines[start]?.trim() === "") start++;
  return lines.slice(start).join("\n");
}

/* ─────────── localStorage helpers ─────────── */
const TASK_KEY = "md:tasks";
const SETTINGS_KEY = "md:settings";
const noteKey = (wk) => `md:notes:${wk}`;

export function saveTasks(activeTasks, completedTasks) {
  const md = tasksToMarkdown(activeTasks, completedTasks);
  localStorage.setItem(TASK_KEY, md);
}

export function loadTasks() {
  const md = localStorage.getItem(TASK_KEY);
  return markdownToTasks(md);
}

export function saveNote(dateStr, content) {
  const wk = weekKey(dateStr);
  const range = weekRange(dateStr);
  const md = noteToMarkdown(wk, range, content);
  localStorage.setItem(noteKey(wk), md);
}

export function loadNote(dateStr) {
  const wk = weekKey(dateStr);
  const md = localStorage.getItem(noteKey(wk));
  return markdownToNote(md);
}

export function loadNoteRaw(dateStr) {
  const wk = weekKey(dateStr);
  return localStorage.getItem(noteKey(wk)) || "";
}

export function saveSettings(settings) {
  localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));
}

export function loadSettings() {
  try {
    return JSON.parse(localStorage.getItem(SETTINGS_KEY)) || {};
  } catch {
    return {};
  }
}

/* ─────────── Attachments per-week ─────────── */
const attKey = (wk) => `md:attachments:${wk}`;

export function saveAttachments(dateStr, attachments) {
  const wk = weekKey(dateStr);
  localStorage.setItem(attKey(wk), JSON.stringify(attachments));
}

export function loadAttachments(dateStr) {
  const wk = weekKey(dateStr);
  try {
    return JSON.parse(localStorage.getItem(attKey(wk))) || [];
  } catch {
    return [];
  }
}

/* ─────────── Export all as .md files (zipped via download) ─────────── */
export function exportAllMarkdown(activeTasks, completedTasks) {
  const files = [];

  // tasks.md
  files.push({ name: "tasks.md", content: tasksToMarkdown(activeTasks, completedTasks) });

  // notes/*.md
  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (key?.startsWith("md:notes:")) {
      const wk = key.replace("md:notes:", "");
      const content = localStorage.getItem(key);
      files.push({ name: `notes/${wk}.md`, content });
    }
  }

  return files;
}

/* ─────────── Simple Markdown → HTML renderer ─────────── */
export function renderMarkdown(md) {
  if (!md || !md.trim()) return "<p style='opacity:0.3'><em>Empty</em></p>";
  return md
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/_(.+?)_/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>)/gs, "<ul>$1</ul>")
    .replace(/<\/ul>\s*<ul>/g, "")
    .replace(/\n{2,}/g, "<br/><br/>")
    .replace(/\n/g, "<br/>");
}

/* ─────────── Import from .md file content ─────────── */
export function importTasksMarkdown(mdContent) {
  return markdownToTasks(mdContent);
}

export function importNoteMarkdown(filename, mdContent) {
  // filename like "2026-W14.md"
  const wk = filename.replace(".md", "");
  localStorage.setItem(noteKey(wk), mdContent);
}
