/* ──────────────────────────────────────────────────────
   markdownDb.js — Markdown-as-DB serializer / parser
   
   Storage keys in localStorage:
     md:tasks        → tasks.md content
     md:notes:YYYY-Www → one key per ISO week
     md:settings     → small JSON blob (nextTaskId, etc.)
   ────────────────────────────────────────────────────── */

/* ── ISO week helpers ── */
export function getISOWeek(dateStr) {
  const d = new Date(dateStr + "T12:00:00");
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const weekNo = Math.ceil(((d - yearStart) / 86400000 + 1) / 7);
  return { year: d.getUTCFullYear(), week: weekNo };
}

export function weekKey(dateStr) {
  const { year, week } = getISOWeek(dateStr);
  return `${year}-W${String(week).padStart(2, "0")}`;
}

export function weekRange(dateStr) {
  const d = new Date(dateStr + "T12:00:00");
  const day = d.getDay();
  const diffMon = d.getDate() - day + (day === 0 ? -6 : 1);
  const mon = new Date(d.getFullYear(), d.getMonth(), diffMon);
  const sun = new Date(mon);
  sun.setDate(mon.getDate() + 6);
  const fmt = (dt) =>
    dt.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  return `${fmt(mon)} – ${fmt(sun)}, ${sun.getFullYear()}`;
}

/* ── Time formatting ── */
const pad2 = (n) => String(n).padStart(2, "0");
export function fmtTime(s) {
  return `${pad2(Math.floor(s / 3600))}:${pad2(Math.floor((s % 3600) / 60))}:${pad2(s % 60)}`;
}

/* ── Per-task notepad notes (multi-line via fenced block) ── */
function notesToMarkdown(notes) {
  if (!notes) return `- **Notes:** (empty)\n`;
  let ticks = 3;
  while (notes.includes("`".repeat(ticks))) ticks++;
  const fence = "`".repeat(ticks);
  return `- **Notes:**\n${fence}notes\n${notes}\n${fence}\n`;
}

/* ─────────── TASKS → Markdown ─────────── */
export function tasksToMarkdown(activeTasks, completedTasks) {
  let md = `# Tasks\n\n`;
  md += `> Auto-generated by Calendar Task App. Do not reorder fields.\n\n`;

  md += `## Active\n\n`;
  if (activeTasks.length === 0) {
    md += `_No active tasks._\n\n`;
  } else {
    for (const t of activeTasks) {
      md += `### T${t.id}\n`;
      md += `- **Description:** ${t.description || "(empty)"}\n`;
      md += `- **Time:** ${fmtTime(t.timeOnTask)} (${t.timeOnTask}s)\n`;
      md += `- **Started:** ${t.startDate}\n`;
      md += notesToMarkdown(t.notes);
      md += `\n`;
    }
  }

  md += `## Completed\n\n`;
  const dateKeys = Object.keys(completedTasks).sort().reverse();
  if (dateKeys.length === 0) {
    md += `_No completed tasks._\n`;
  } else {
    for (const dk of dateKeys) {
      md += `### ${dk}\n\n`;
      for (const ct of completedTasks[dk]) {
        md += `#### T${ct.id}\n`;
        md += `- **Description:** ${ct.description || "(empty)"}\n`;
        md += `- **Time:** ${fmtTime(ct.timeOnTask)} (${ct.timeOnTask}s)\n`;
        md += `- **Completed:** ${ct.completedAt}\n`;
        md += notesToMarkdown(ct.notes);
        md += `\n`;
      }
    }
  }

  return md;
}

/* ─────────── Markdown → TASKS ─────────── */
export function markdownToTasks(md) {
  const activeTasks = [];
  const completedTasks = {};

  if (!md || !md.trim()) return { activeTasks, completedTasks };

  const lines = md.split("\n");
  let section = null; // 'active' | 'completed'
  let currentDateKey = null;
  let currentTask = null;
  let parsingCompleted = false;
  let notesFence = null; // e.g. "```" while collecting notepad body
  let notesLines = [];

  const flushNotes = () => {
    if (!currentTask || notesFence === null) return;
    currentTask.notes = notesLines.join("\n");
    notesFence = null;
    notesLines = [];
  };

  for (const line of lines) {
    // Inside a notes fenced block — collect until matching close fence
    if (notesFence !== null) {
      if (line.trim() === notesFence) {
        flushNotes();
      } else {
        notesLines.push(line);
      }
      continue;
    }

    const trimmed = line.trim();

    // Section headers
    if (trimmed === "## Active") {
      section = "active";
      parsingCompleted = false;
      continue;
    }
    if (trimmed === "## Completed") {
      // Flush the last Active task before leaving that section; otherwise it
      // stays as currentTask and the first #### in Completed wrongly files it
      // under the first completed date (todo / in-progress tasks "become" done).
      flushNotes();
      if (currentTask && section === "active") {
        activeTasks.push(currentTask);
        currentTask = null;
      }
      section = "completed";
      parsingCompleted = true;
      continue;
    }

    // Task ID lines (### T0, #### T0)
    const taskMatch = trimmed.match(/^#{3,4}\s+T(\d+)$/);
    if (taskMatch) {
      // Save previous task
      flushNotes();
      if (currentTask) {
        if (parsingCompleted && currentDateKey) {
          if (!completedTasks[currentDateKey]) completedTasks[currentDateKey] = [];
          completedTasks[currentDateKey].push(currentTask);
        } else if (!parsingCompleted) {
          activeTasks.push(currentTask);
        }
      }
      currentTask = {
        id: parseInt(taskMatch[1]),
        description: "",
        timeOnTask: 0,
        startDate: new Date().toISOString(),
        notes: "",
      };
      continue;
    }

    // Date key for completed section (### 2026-04-01)
    if (parsingCompleted) {
      const dateMatch = trimmed.match(/^### (\d{4}-\d{2}-\d{2})$/);
      if (dateMatch) {
        // Save previous task if any
        flushNotes();
        if (currentTask && currentDateKey) {
          if (!completedTasks[currentDateKey]) completedTasks[currentDateKey] = [];
          completedTasks[currentDateKey].push(currentTask);
          currentTask = null;
        }
        currentDateKey = dateMatch[1];
        continue;
      }
    }

    // Field parsing
    if (currentTask) {
      const descMatch = trimmed.match(/^-\s+\*\*Description:\*\*\s+(.+)$/);
      if (descMatch) {
        currentTask.description = descMatch[1] === "(empty)" ? "" : descMatch[1];
        continue;
      }
      const timeMatch = trimmed.match(/\((\d+)s\)/);
      if (timeMatch && trimmed.includes("**Time:**")) {
        currentTask.timeOnTask = parseInt(timeMatch[1]);
        continue;
      }
      const startMatch = trimmed.match(/^-\s+\*\*Started:\*\*\s+(.+)$/);
      if (startMatch) {
        currentTask.startDate = startMatch[1];
        continue;
      }
      const compMatch = trimmed.match(/^-\s+\*\*Completed:\*\*\s+(.+)$/);
      if (compMatch) {
        currentTask.completedAt = compMatch[1];
        currentTask.dateKey = currentDateKey;
        continue;
      }
      // Notes: empty, inline, or opening of a ```notes fence on the next line
      const notesEmpty = trimmed.match(/^-\s+\*\*Notes:\*\*\s+\(empty\)$/);
      if (notesEmpty) {
        currentTask.notes = "";
        continue;
      }
      const notesInline = trimmed.match(/^-\s+\*\*Notes:\*\*\s+(.+)$/);
      if (notesInline) {
        currentTask.notes = notesInline[1];
        continue;
      }
      if (trimmed.match(/^-\s+\*\*Notes:\*\*\s*$/)) {
        // Expect a fenced block on a following line
        continue;
      }
      const fenceOpen = trimmed.match(/^(`{3,})notes\s*$/);
      if (fenceOpen) {
        notesFence = fenceOpen[1];
        notesLines = [];
        continue;
      }
    }
  }

  // Save final task
  flushNotes();
  if (currentTask) {
    if (parsingCompleted && currentDateKey) {
      if (!completedTasks[currentDateKey]) completedTasks[currentDateKey] = [];
      completedTasks[currentDateKey].push(currentTask);
    } else if (!parsingCompleted) {
      activeTasks.push(currentTask);
    }
  }

  return { activeTasks, completedTasks };
}

/* ─────────── NOTES → Markdown ─────────── */
export function noteToMarkdown(wk, range, content) {
  return `# ${wk} — ${range}\n\n${content}`;
}

export function markdownToNote(md) {
  if (!md || !md.trim()) return "";
  const lines = md.split("\n");
  // Skip the H1 header line and the blank line after it
  let start = 0;
  if (lines[0]?.startsWith("# ")) start = 1;
  if (lines[start]?.trim() === "") start++;
  return lines.slice(start).join("\n");
}

/* ─────────── localStorage helpers ─────────── */
const TASK_KEY = "md:tasks";
const SETTINGS_KEY = "md:settings";
const noteKey = (wk) => `md:notes:${wk}`;

export function saveTasks(activeTasks, completedTasks) {
  const md = tasksToMarkdown(activeTasks, completedTasks);
  localStorage.setItem(TASK_KEY, md);
}

export function loadTasks() {
  const md = localStorage.getItem(TASK_KEY);
  return markdownToTasks(md);
}

export function saveNote(dateStr, content) {
  const wk = weekKey(dateStr);
  const range = weekRange(dateStr);
  const md = noteToMarkdown(wk, range, content);
  localStorage.setItem(noteKey(wk), md);
}

export function loadNote(dateStr) {
  const wk = weekKey(dateStr);
  const md = localStorage.getItem(noteKey(wk));
  return markdownToNote(md);
}

export function loadNoteRaw(dateStr) {
  const wk = weekKey(dateStr);
  return localStorage.getItem(noteKey(wk)) || "";
}

export function saveSettings(settings) {
  localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));
}

export function loadSettings() {
  try {
    return JSON.parse(localStorage.getItem(SETTINGS_KEY)) || {};
  } catch {
    return {};
  }
}

/* ─────────── Attachments per-week ─────────── */
const attKey = (wk) => `md:attachments:${wk}`;

export function saveAttachments(dateStr, attachments) {
  const wk = weekKey(dateStr);
  localStorage.setItem(attKey(wk), JSON.stringify(attachments));
}

export function loadAttachments(dateStr) {
  const wk = weekKey(dateStr);
  try {
    return JSON.parse(localStorage.getItem(attKey(wk))) || [];
  } catch {
    return [];
  }
}

/* ─────────── Export all as .md files (zipped via download) ─────────── */
export function exportAllMarkdown(activeTasks, completedTasks) {
  const files = [];

  // tasks.md
  files.push({ name: "tasks.md", content: tasksToMarkdown(activeTasks, completedTasks) });

  // notes/*.md
  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (key?.startsWith("md:notes:")) {
      const wk = key.replace("md:notes:", "");
      const content = localStorage.getItem(key);
      files.push({ name: `notes/${wk}.md`, content });
    }
  }

  return files;
}

/** CRC32 table for ZIP (store method, no compression). */
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let j = 0; j < 8; j++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[i] = c;
  }
  return t;
})();

function crc32(data) {
  let c = 0xffffffff;
  for (let i = 0; i < data.length; i++) c = CRC_TABLE[(c ^ data[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function u16(n) {
  const b = new Uint8Array(2);
  new DataView(b.buffer).setUint16(0, n, true);
  return b;
}

function u32(n) {
  const b = new Uint8Array(4);
  new DataView(b.buffer).setUint32(0, n, true);
  return b;
}

function concatBytes(parts) {
  const total = parts.reduce((n, p) => n + p.length, 0);
  const out = new Uint8Array(total);
  let off = 0;
  for (const p of parts) { out.set(p, off); off += p.length; }
  return out;
}

/** Build an uncompressed ZIP Blob preserving folder paths (e.g. notes/2026-W14.md). */
export function filesToZipBlob(files) {
  const encoder = new TextEncoder();
  const localParts = [];
  const centralParts = [];
  let offset = 0;

  for (const file of files) {
    const nameBytes = encoder.encode(file.name);
    const data = typeof file.content === "string" ? encoder.encode(file.content) : file.content;
    const crc = crc32(data);
    const size = data.length;

    const localHeader = concatBytes([
      u32(0x04034b50), // local file header signature
      u16(20),         // version needed
      u16(0),          // flags
      u16(0),          // compression: store
      u16(0), u16(0),  // time, date
      u32(crc),
      u32(size),
      u32(size),
      u16(nameBytes.length),
      u16(0),          // extra length
      nameBytes,
    ]);

    localParts.push(localHeader, data);

    const centralHeader = concatBytes([
      u32(0x02014b50), // central directory signature
      u16(20),         // version made by
      u16(20),         // version needed
      u16(0),          // flags
      u16(0),          // compression: store
      u16(0), u16(0),  // time, date
      u32(crc),
      u32(size),
      u32(size),
      u16(nameBytes.length),
      u16(0),          // extra length
      u16(0),          // comment length
      u16(0),          // disk start
      u16(0),          // internal attrs
      u32(0),          // external attrs
      u32(offset),     // local header offset
      nameBytes,
    ]);
    centralParts.push(centralHeader);
    offset += localHeader.length + size;
  }

  const centralDir = concatBytes(centralParts);
  const endRecord = concatBytes([
    u32(0x06054b50),
    u16(0), u16(0),
    u16(files.length),
    u16(files.length),
    u32(centralDir.length),
    u32(offset),
    u16(0),
  ]);

  return new Blob([concatBytes([...localParts, centralDir, endRecord])], { type: "application/zip" });
}

/** Collect all markdown files and return a downloadable ZIP Blob. */
export function exportAllMarkdownZip(activeTasks, completedTasks) {
  return filesToZipBlob(exportAllMarkdown(activeTasks, completedTasks));
}

async function inflateRaw(data) {
  const ds = new DecompressionStream("deflate-raw");
  const stream = new Blob([data]).stream().pipeThrough(ds);
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

/** Parse a ZIP ArrayBuffer into { name, content } text files (store + deflate). */
export async function parseZip(buffer) {
  const view = new DataView(buffer);
  const bytes = new Uint8Array(buffer);
  let eocd = -1;
  for (let i = bytes.length - 22; i >= Math.max(0, bytes.length - 65558); i--) {
    if (view.getUint32(i, true) === 0x06054b50) { eocd = i; break; }
  }
  if (eocd < 0) throw new Error("Invalid ZIP file");

  const count = view.getUint16(eocd + 8, true);
  let offset = view.getUint32(eocd + 16, true);
  const decoder = new TextDecoder();
  const files = [];

  for (let i = 0; i < count; i++) {
    if (view.getUint32(offset, true) !== 0x02014b50) throw new Error("Corrupt ZIP central directory");
    const method = view.getUint16(offset + 10, true);
    const compSize = view.getUint32(offset + 20, true);
    const nameLen = view.getUint16(offset + 28, true);
    const extraLen = view.getUint16(offset + 30, true);
    const commentLen = view.getUint16(offset + 32, true);
    const localOff = view.getUint32(offset + 42, true);
    const name = decoder.decode(bytes.subarray(offset + 46, offset + 46 + nameLen));
    offset += 46 + nameLen + extraLen + commentLen;

    if (name.endsWith("/")) continue;

    const localNameLen = view.getUint16(localOff + 26, true);
    const localExtraLen = view.getUint16(localOff + 28, true);
    const dataStart = localOff + 30 + localNameLen + localExtraLen;
    let data = bytes.subarray(dataStart, dataStart + compSize);

    if (method === 8) data = await inflateRaw(data);
    else if (method !== 0) throw new Error(`Unsupported ZIP compression method: ${method}`);

    files.push({ name, content: decoder.decode(data) });
  }
  return files;
}

/** Map any nested path to tasks.md or notes/YYYY-Www.md when possible. */
export function normalizeImportPath(name) {
  const parts = name.replace(/\\/g, "/").split("/").filter(Boolean);
  const base = parts[parts.length - 1] || "";
  const notesIdx = parts.findIndex((p) => p === "notes");
  if (notesIdx >= 0 && /^\d{4}-W\d{2}\.md$/.test(parts[notesIdx + 1] || "")) {
    return `notes/${parts[notesIdx + 1]}`;
  }
  if (base === "tasks.md") return "tasks.md";
  if (/^\d{4}-W\d{2}\.md$/.test(base)) return `notes/${base}`;
  return null;
}

/**
 * Apply exported markdown files into localStorage / return parsed tasks.
 * Accepts paths like tasks.md, notes/2026-W14.md, or nested equivalents.
 */
export function importMarkdownFiles(files) {
  let tasksResult = null;
  let notesImported = 0;

  for (const f of files) {
    const path = normalizeImportPath(f.name);
    if (!path) continue;
    if (path === "tasks.md") {
      tasksResult = markdownToTasks(f.content);
      saveTasks(tasksResult.activeTasks, tasksResult.completedTasks);
    } else if (/^notes\/\d{4}-W\d{2}\.md$/.test(path)) {
      const wk = path.slice("notes/".length, -".md".length);
      localStorage.setItem(noteKey(wk), f.content);
      notesImported++;
    }
  }

  return { tasksResult, notesImported };
}

/* ─────────── Simple Markdown → HTML renderer ─────────── */
export function renderMarkdown(md) {
  if (!md || !md.trim()) return "<p style='opacity:0.3'><em>Empty</em></p>";
  return md
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/_(.+?)_/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>)/gs, "<ul>$1</ul>")
    .replace(/<\/ul>\s*<ul>/g, "")
    .replace(/\n{2,}/g, "<br/><br/>")
    .replace(/\n/g, "<br/>");
}

/* ─────────── Import from .md file content ─────────── */
export function importTasksMarkdown(mdContent) {
  return markdownToTasks(mdContent);
}

export function importNoteMarkdown(filename, mdContent) {
  // filename like "2026-W14.md"
  const wk = filename.replace(".md", "");
  localStorage.setItem(noteKey(wk), mdContent);
}
